In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

nyc_data = pd.read_csv('https://raw.githubusercontent.com/DanielleRomanoff/DS-Unit-1-Project_Dog_Bites/master/NYC%20dog%20bite%20data.csv')
nyc_data.shape

(8707, 9)

In [32]:
pd.set_option('display.max_rows', 1000)
nyc_data.isna().sum()

UniqueID         0
DateOfBite       0
Species          0
Breed            1
Age           3245
Gender           0
SpayNeuter       0
Borough          0
ZipCode       1864
dtype: int64

In [33]:
# nyc_data = nyc_data.drop(nyc_data.loc[nyc_data['Gender'] == 'U'].index)
nyc_data = nyc_data[nyc_data.Gender != 'U']
nyc_data.head()

,UniqueID,DateOfBite,Species,Breed,Age,Gender,SpayNeuter,Borough,ZipCode
0,8140,December 02 2015,DOG,Pug,7,F,True,Staten Island,NaN
1,1,January 27 2015,DOG,Jack Russ,11,M,False,Brooklyn,11217
4,4,December 26 2014,DOG,Doberman Pinscher,NaN,M,False,Brooklyn,11204
6,6,January 31 2015,DOG,Chihuahua Crossbreed,3,M,False,Brooklyn,NaN
7,7,January 31 2015,DOG,German Shepherd Crossbreed,NaN,F,False,Brooklyn,11220

In [34]:
nyc_data_new = nyc_data.groupby(['Breed', 'Gender', 'SpayNeuter']).count().sort_values(by = ['Breed', 'UniqueID'], ascending = False)
nyc_data_modified = nyc_data_new.drop(index = ['UNKNOWN', 'Mixed/Other', 'TERRIER', 'MIXED', 'MIXED BREED', 'PIT BULL MIX', 'LABRADOR MIX', 'HUSKY', 'SHEPHERD', 'SHEPERD', 'MUTT', 'TERRIER MIX'])
nyc_bite_data = nyc_data_modified[nyc_data_modified.UniqueID >= 0]
nyc_bite_final = pd.DataFrame(nyc_bite_data, columns = ['UniqueID'])
nyc_bite_final.head(10)

                                                UniqueID
Breed                        Gender SpayNeuter
Yorkshire Terrier Crossbreed M      False              6
                                    True               5
                             F      False              1
                                    True               1
Yorkshire Terrier            M      True              68
                                    False             41
                             F      False             21
                                    True              21
YORKSHIRE/SHIH TZU MIX       M      False              1
YORKSHIRE/ TIBETAN TERRIER   M      True               1

In [35]:
nyc_bite_data.shape

(1297, 6)

In [39]:
males = nyc_data[nyc_data['Gender'] == 'M']
# ['Breed'].value_counts()
# nyc_data.Gender.value_counts()
neuters = males[males['SpayNeuter'] == True]
unneutered = males[males['SpayNeuter'] != True]
# males['SpayNeuter'].value_counts()
neutered_males = neuters['Breed'].value_counts()
unneutered_males = unneutered['Breed'].value_counts()
total_males = males['Gender'].value_counts()
print(neutered_males)
print(total_males)

M    4121
Name: Gender, dtype: int64

In [40]:
nyc_data.describe()

          UniqueID
count  5729.000000
mean   4404.746204
std    2533.667874
min       1.000000
25%    2205.000000
50%    4470.000000
75%    6601.000000
max    8705.000000

In [41]:
nyc_bite_data.describe()

,UniqueID,DateOfBite,Species,Age,Borough,ZipCode
count,1297.000000,1297.000000,1297.000000,1297.000000,1297.000000,1297.000000
mean,4.148805,4.148805,4.148805,3.901311,4.148805,3.561295
std,16.240816,16.240816,16.240816,14.603329,16.240816,14.027458
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,394.000000,394.000000,394.000000,341.000000,394.000000,334.000000

In [42]:
females = nyc_data[nyc_data['Gender'] == 'F']
# ['Breed'].value_counts()
# nyc_data.Gender.value_counts()
spayed = females[females['SpayNeuter'] == True]
not_spayed = females[females['SpayNeuter'] != True]
# females['SpayNeuter'].value_counts()
spayed_females = spayed['Breed'].value_counts()
not_spayed_females = not_spayed['Breed'].value_counts()
total_females = females['Gender'].value_counts()
print(spayed_females)
print(not_spayed_females)
print(total_females)

Pit Bull                                        108
American Pit Bull Mix / Pit Bull Mix             51
American Pit Bull Terrier/Pit Bull               36
German Shepherd                                  25
Mixed/Other                                      24
Chihuahua                                        24
Yorkshire Terrier                                21
Labrador Retriever Crossbreed                    21
Shih Tzu                                         20
Maltese                                          16
Labrador Retriever                               15
German Shepherd Crossbreed                       12
Jack Russ                                        12
Bichon Frise                                     11
Shiba Inu                                        10
American Staffordshire Terrier                    9
PIT BULL MIX                                      9
Bull dog                                          9
Dachshund Smooth Coat                             8
Siberian Husky                                    8
Rottweiler                                        8
Beagle                                            7
Golden Retriever                                  7
Poodle, Standard                                  7
Boxer                                             7
Australian Shepherd                               6
TERRIER MIX                                       6
Boston Terrier                                    6
Cocker Spaniel                                    6
Bull Dog, English                                 5
Bull Dog, French                                  5
Pomeranian                                        5
MUTT                                              5
Pekingese                                         5
Cane Corso                                        4
Chihuahua Crossbreed                              4
Puggle                                            4
BORDER COLLIE MIX                                 4
SHEPHERD MIX                                      4
MIXED                                             4
Labradoodle                                       4
MIXED BREED                                       4
Shar-Pei, Chinese                                 3
American Eskimo                                   3
Poodle, Toy                                       3
Staffordshire Bull Terrier                        3
TERRIER                                           3
Cairn Terrier                                     3
AMERICAN BULLY                                    3
Beagle Crossbreed                                 3
BOXER MIX                                         3
Rhodesian Ridgeback                               3
BEAGLE MIX                                        3
Jindo Dog,                                        3
Mastiff, Bull                                     3
Weimaraner                                        3
Collie, Border                                    2
Schnauzer, Standard                               2
Miniature Pinscher                                2
Dachshund, Long Haired                            2
Dachshund Smooth Coat Miniature                   2
Doberman Pinscher                                 2
DACHSHUND MIX                                     2
SHEPHERD                                          2
Collie, Smooth Coat                               2
Pug                                               2
Border Terrier                                    2
Akita                                             2
LABRADOR MIX                                      2
SAINT BERNARD MIX                                 2
Lhasa Apso                                        2
Brittany Spaniel                                  2
RAT TERRIER                                       2
BELGIAN SHEPHERD                                  2
HOUND                                             2
Dalmatian                                         2
BOXER X                                           2
Poodle, Miniature                                 2
Cocker Spaniel Crossbreed                         2
Chow Chow                                         2
HUSKY                                             2
LABRADOR / PIT BULL MIX                           2
Great Dane                                        2
West High White Terrier                           2
PIT BULL / LABRADOR MIX                           2
MORKIE                                            2
Bernese Mountain                                  2
DACHSHUND X                                       2
Wheaton Terrier                                   2
AUSTRALIAN CATTLE DOG                             2
BEAGLE                                            2
BEAGLE/LAB X                                      1
BLACK RUSSIAN TERRIER                             1
PARSON RUSSELL TERRIEER                           1
MALTESE/SHIH TZU                                  1
JAPANESE SHIBA                                    1
BOXER/PIT BULL X                                  1
BORDER COLLIE/LAB                                 1
MIX- BOXER                                        1
MINI POODLE X                                     1
BOXER/HOUND/PITBULL                               1
PIT BULL TERRIER                                  1
PIT BULL/AMERICAN BULL                            1
SHELTIE MIX                                       1
ITALIAN MASTIFF/CANE CORSO X                      1
GERMAN SHEPARD/ LABRADOR RETRIEVER X              1
SHIH TZU/DACHSHUND  X                             1
PITBULL/LAB MIX                                   1
PIT/DALMATIAN MIX                                 1
Portuguese Water Dog                              1
PITBULL/LAB RETRIEVER                             1
HUSKY MIX                                         1
BEAGLE/JACK RUSSELL                               1
Schnauzer, Miniature                              1
MASTIFF MIX                                       1
LABRADOR / CHOW CHOW MIX                          1
CATAHOULA TERRIER MIX                             1
Belgian Sheepdog                                  1
BASSET HOUND X                                    1
Belgian Malinois                                  1
SHIH TZU/MALTESE X                                1
BOXER                                             1
LABRADOR / GREAT DANE MIX                         1
POODLE                                            1
MALTESE/POODLE                                    1
DUNKER                                            1
FOX HOUND                                         1
BOX TERR X                                        1
AMERICAN STAFFORDSHIRE TERRIER / PIT BULL         1
SCOTTIE/LHASA AHPSO                               1
SHIBA MIX                                         1
WELSH/CORGI                                       1
Norfolk Terrier                                   1
POODLE MIN/ YORKSHIRE TER                         1
Papillon                                          1
SHEPHERD / PIT BULL MIX                           1
PIT BULL / SHEPHERD MIX                           1
JACK RUSS / CHIHUAHUA MIX                         1
MALTESE / POODLE                                  1
Yorkshire Terrier Crossbreed                      1
STAFFORDHIRE/ENGLISH BULLDOG                      1
Cock-A-Poo                                        1
MALTESE / SHIH TZU MIX                            1
MINI PINSCHER/YORKSHIRE TERRIER                   1
LHASA APSO MIX                                    1
Irish Terrier                                     1
BOSTON TERRIER MIX                                1
CHOW MIX                                          1
LAB RETRIEVER/GERM SHEP                           1
POODLE MIX, TEACUP                                1
PIT BULL/TERRIER/BOXER                            1
STAFFORDSHIRE TERRIER/PITBULL MIX                 1
LAB- X                                            1
PITBULL/LABRADOR RETRIEVER                        1
LAB/PIT BULL/CHIHUAHUA X                          1
AMERICAN BULLDOG/GREAT PYRENEES                   1
LAB/SHEPHERD X                                    1
BOSTON BORDER TERRIER                             1
RETRIEVER MIX                                     1
POODLE MIX                                        1
BICHON FRISE / TERRIER MIX                        1
YORKIE POO- YORKSHIRE TERRIER/MALTESE/POODLE      1
MIXED TERRIER                                     1
BEAGLE/ ENG SPRINGER SPANIEL                      1
LABRADOR RETR./JACK RUSS. TERR.                   1
MALTESE / POODLE MIX                              1
ROTTWEILER/BOXER                                  1
BORDER COLLIE/JACK RUSSELL                        1
PIT BULL / ROTTWEILER MIX                         1
LAB/ PIT BULL MIX                                 1
PIT BULL                                          1
AUSTRALIAN CATTLE MIX                             1
GOLDEN RETRIEVER MIXED                            1
ENGLIH BULLDOG                                    1
MIXED BREED (MINI AUSSIE MIX)                     1
PUG / JACK RUSS MIX                               1
PIT BULL X/FRENCH BULLDOG                         1
CHIHUAHUA / POMERANIAN MIX                        1
Bull Terrier                                      1
LAB/RAT TERRIER X                                 1
POODLE CHIHUAHUA                                  1
YORKIE / POODLE MIX                               1
MINIATURE LABRADOODLE                             1
MALTESE- X                                        1
Havanese                                          1
JINDO / JACK RUSS MIX                             1
Pointer, German Shorthaired                       1
BOXER/BOSTON TERRIER                              1
LARGE BREED MIX                                   1
SHEPHERD X                                        1
SHIH TZU/BICHON FRISE MIX                         1
SHIH TZU/ POODLE MIX                              1
BOXER/PIT BULL                                    1
WHIPPET X                                         1
CATAHOULA CUR                                     1
WIRED HAIR TERRIER X                              1
PITBULL/ LABRADOR MIX                             1
BELGIUM SHEPARD                                   1
GERMAN SHEPARD/PITBULL                            1
BASENJI                                           1
HOUND X                                           1
HOUND MIX                                         1
RED-NOSED PIT BULL                                1
BLUE HEELER/ AUSTRALIAN CATTLE MIX                1
AMER STAFFORDSHIRE X                              1
CHIHUAHUA                                         1
JSCK RUSSEL/DALMATION                             1
AMERICAN STAFFORD MIX                             1
SHIH TZU CROSSBREED                               1
Mastiff, Old English                              1
SHAR-PEI/PIT BULL                                 1
STAFFORDSHIRE TERR                                1
COATED XOLO                                       1
GREYHOUND / LABRADOR MIX                          1
SHEPARD X                                         1
DAUSHAUND-X                                       1
MALTESE / YORKSHIRE                               1
PITBULL MIX                                       1
POTCAKE                                           1
LABRADOODLE                                       1
FRENCH BULLDOG/ STAFFORSHIRE TERRIER MIX          1
SHEPHERD/TERRIER X                                1
PIT BULL MIXED                                    1
HAVANESE/ POODLE MIX                              1
HOUND / GERMAN SHEPHERD MIX                       1
BASSET HOUND MIX                                  1
HUSKY X                                           1
DACHSHUND                                         1
MALTESE MIX                                       1
BOXER/ AMERICAN STAFFORDSHIRE                     1
Silky Terrier                                     1
CHOW/SCHNAUZER X                                  1
HUSKY LABRADOR                                    1
SCHNAUZER/POODLE                                  1
STAFFORDSHIRE                                     1
LABRADOR BOXER                                    1
GREAT PYREENES X                                  1
MULTI COLLAR TERRIER                              1
MONGREL MIX                                       1
CHIHUAHUA SH X                                    1
Vizsla                                            1
AMER STAFF/AM PIT BULL TERR                       1
Collie Crossbreed                                 1
DOXXIN                                            1
HUSKY/LAB X                                       1
PEKINGESE -X                                      1
JACK RUSSELL TERRIER/ BASENJI MIX                 1
COLLIE/TERRIER MIX                                1
BEAGLE/ SHEPHERED                                 1
MALINOIS MIX                                      1
PIT BULL TERRIER MIX                              1
JACK RUSS / SHIH TZU                              1
STAFFORDSHIRE / PIT BULL MIX                      1
LABRADOR / HOUND MIX                              1
JACK RUSS-X                                       1
LAB/COLLIE X                                      1
HEELER X                                          1
PIT/BOXER                                         1
BOXER / PIT BULL MIX                              1
AMERICAN BULLDOG                                  1
PITBULL TERRIER MIX                               1
Bouvier Des Flandres                              1
SCOTTISH TERRIER                                  1
BORDER COLLIE & WHIPPET MIX                       1
COLLIE MIX                                        1
SHARPEI                                           1
SHIH TZU MIX                                      1
AUS KELPIE/ LAB RETR                              1
2 DOGS: TERR X & DOBERMAN                         1
ROTWEILLER/LABRADOR RETRIEVER                     1
CHIHUAHUA MIX                                     1
Name: Breed, dtype: int64
Pit Bull                                167
American Pit Bull Mix / Pit Bull Mix     50
Shih Tzu                                 44
American Pit Bull Terrier/Pit Bull       36
German Shepherd                          30
Chihuahua                                26
Mixed/Other                              22
Yorkshire Terrier                        21
Maltese                                  21
Rottweiler                               12
Cocker Spaniel                           12
Labrador Retriever                       11
Jack Russ                                10
American Staffordshire Terrier           10
Siberian Husky                            9
Poodle, Standard                          8
Beagle                                    7
Pomeranian                                6
Shiba Inu                                 6
Doberman Pinscher                         6
German Shepherd Crossbreed                5
MIXED                                     5
Pekingese                                 5
PIT BULL MIX                              5
TERRIER MIX                               5
Chihuahua Crossbreed                      5
Cane Corso                                4
Bull dog                                  4
West High White Terrier                   4
Poodle, Miniature                         4
Staffordshire Bull Terrier                4
MIXED BREED                               4
Lhasa Apso                                4
Chow Chow                                 4
Poodle, Toy                               3
Bull Dog, English                         3
Miniature Pinscher                        3
Boxer                                     3
Labrador Retriever Crossbreed             3
RAT TERRIER                               2
POODLE                                    2
Dachshund Smooth Coat                     2
Scottish Terrier                          2
CORGI MIX                                 2
Bull Dog, French                          2
JACK RUSSELL X                            2
POODLE MIX                                2
RED NOSE PIT BULL                         2
Shar-Pei, Chinese                         2
TERRIER                                   2
PIT BULL/LAB X                            2
Beagle Crossbreed                         2
MALTESE MIX                               2
PIT BULL TER/ALASKAN HUSKY                2
Australian Shepherd                       2
MUTT                                      2
ENGLISH COCKER SPANIEL                    1
ENGLISH MASTIFF                           1
SHIH TZU MIX MALTESE                      1
LAB/BASSET HOUND X                        1
CHINESE TIEN YUN CHU                      1
Cock-A-Poo                                1
FRENCH / ENGLISH BULL DOG MIX             1
GERMAN SHEPERD/AUSTRALIAN MIX             1
PITBULL/BOXER                             1
NEWFOUNDLAND                              1
GOLDEN RETRIEVER / DOODLE MIX             1
CHIHUAHUA- X                              1
TERRIER / CHIHUAHUA MIX                   1
POMERANIAN/YORKIE                         1
BULLY                                     1
BORDER COLLIE                             1
GOLDEN LABRADOR MIX                       1
Havanese                                  1
COLLIE                                    1
Jindo Dog,                                1
YORKIE / JACK RUSSELL MIX                 1
LABRADOR / PIT BULL                       1
POMERANIAN / CHIHUAHUA MIX                1
AMERICAN BULL                             1
AMERICAN STAFF/AKITA                      1
PIT BULL / GERMAN SHEPHERD MIX            1
Golden Retriever                          1
PIT BULL                                  1
SHEEP DOG                                 1
PIT BULL /GERMAN SHEPHERD MIX             1
Papillon                                  1
Weimaraner                                1
TERRIER/ YORKIE                           1
Yorkshire Terrier Crossbreed              1
ENGLISH BULL DOG                          1
CHIHUAHUA/YORKSHIRE MIX                   1
MIX BREED/ PIT BULL                       1
PIT-BULL LAB X                            1
JACK RUSS / SHIH TZU MIX                  1
SHIH TZU MIX                              1
WESTY                                     1
BOXER/PITBULL MIX                         1
AMERICAN PITBULL/ LABRADOR RETRIEVER      1
DOBERMAN X                                1
Samoyed                                   1
MALSHI                                    1
Newfoundland                              1
Bichon Frise                              1
MALTIPOO X                                1
DACHSHUND MIX                             1
PIT BULL/ SIBERIAN HUSKY                  1
SHEPARD MIX                               1
BLUE NOSED PIT BULL                       1
SIBERIAN HUSKY MIX                        1
CHIHUAHUA SHORTHAIR MIX                   1
SHIH TZU/ POMERANINAN                     1
CHOW/MINI PINCHER                         1
PIT BULL TERRIER                          1
SHIH TZU/ MALTESE                         1
GERMAN SHEPERD POINT MIX                  1
PIT BULL & SILKY TERRIER X                1
SPANIEL MIX                               1
LHATESE                                   1
YELLOW LAB/BEAGLE X                       1
MALTESE X                                 1
PEKINGESE/CHIHUAHUA                       1
AUST KELPIE/AM PIT BULL X                 1
SMALL MIXED BREED                         1
HUSKY                                     1
GOLDEN RETRIVER MIX                       1
Belgian Malinois                          1
SHIH TZU X                                1
CATTLE DOG/BLUE HEELER                    1
BULL TERRIER MIX                          1
BOXER/RHODESIAN RIDGEBACK X               1
Cocker Spaniel Crossbreed                 1
LAB/PIT BULL X                            1

In [43]:
gender = pd.Series(np.where(nyc_data.Gender.values == 'M', 1, 0), nyc_data.index)
spayneuter = pd.Series(np.where(nyc_data.SpayNeuter.values == True, 1, 0), nyc_data.index)

In [55]:
from scipy import stats
from scipy.stats import normaltest
print(normaltest(nyc_bite_final))
print(normaltest(spayed_females))
print(normaltest(not_spayed_females))
print(normaltest(neutered_males))
print(normaltest(unneutered_males))

NormaltestResult(statistic=array([2504.3595128]), pvalue=array([0.]))
NormaltestResult(statistic=454.19973425584317, pvalue=2.353861282045512e-99)
NormaltestResult(statistic=332.73137661200224, pvalue=5.601438739796729e-73)
NormaltestResult(statistic=842.973827238952, pvalue=8.923992993396342e-184)
NormaltestResult(statistic=693.2032665145406, pvalue=2.970456916230831e-151)

In [84]:
from scipy.stats import kruskal
print(kruskal(spayed_females, neutered_males))
print(kruskal(not_spayed_females, unneutered_males))
print(kruskal(neutered_males, unneutered_males))
print(kruskal(spayed_females, not_spayed_females))
print(kruskal(total_males, total_females))

KruskalResult(statistic=0.1653562608023182, pvalue=0.6842722595558332)
KruskalResult(statistic=0.0013962499644603412, pvalue=0.9701928402967256)
KruskalResult(statistic=0.00421575869174184, pvalue=0.9482306308871459)
KruskalResult(statistic=0.08304870565427269, pvalue=0.7732076382954411)
KruskalResult(statistic=1.0, pvalue=0.31731050786291115)

In [83]:
def confidence_interval(data, confidence=0.95):
    data = np.array(data)
    mean = np.mean(data)
    n = len(data)
    stderr = stats.sem(data)
    interval = stderr * stats.t.ppf((1 + confidence) / 2., n - 1)
    return (mean, mean - interval, mean + interval)

def report_confidence_interval(confidence_interval):
    location = "The mean lies within the interval ]{:.2}, {:.2}[".format(
    confidence_interval[1], confidence_interval[2])
    return location

neutered_m = confidence_interval(neutered_males)
print(neutered_m)
nmale_dogs = report_confidence_interval(neutered_m)
print(nmale_dogs)
unneutered_m = confidence_interval(unneutered_males)
print(unneutered_m)
unmale_dogs = report_confidence_interval(unneutered_m)
print(unmale_dogs)
spayed_f = confidence_interval(spayed_females)
print(spayed_f)
sfemale_dogs = report_confidence_interval(spayed_f)
print(sfemale_dogs)
notspayed_f = confidence_interval(not_spayed_females)
print(notspayed_f)
notsfemale_dogs = report_confidence_interval(notspayed_f)
print(notsfemale_dogs)

(3.9942528735632186, 2.943158593427721, 5.045347153698716)
The mean lies within the interval ]2.9, 5.0[
(5.624309392265193, 3.09677111983129, 8.151847664699096)
The mean lies within the interval ]3.1, 8.2[
(3.1660516605166054, 2.179640441804813, 4.1524628792283975)
The mean lies within the interval ]2.2, 4.2[
(4.143646408839779, 2.1018864124751078, 6.185406405204451)
The mean lies within the interval ]2.1, 6.2[

In [60]:
print(neutered_males.mean())
print(neutered_males.std())
print(neutered_males.var())

3.9942528735632186
12.224152703789642
149.4299093255676

In [61]:
print(unneutered_males.mean())
print(unneutered_males.std())
print(unneutered_males.var())

5.624309392265193
24.4537500071244
597.9858894109365

In [62]:
print(spayed_females.mean())
print(spayed_females.std())
print(spayed_females.var())

3.1660516605166054
8.24790156820526
68.02788027880277

In [63]:
print(not_spayed_females.mean())
print(not_spayed_females.std())
print(not_spayed_females.var())

4.143646408839779
13.920860684073732
193.79036218538977

In [86]:
import scipy
print(scipy.stats.ttest_1samp(neutered_males, 0.5))
print(scipy.stats.ttest_1samp(unneutered_males, 0.5))
print(scipy.stats.ttest_1samp(spayed_females, 0.5))
print(scipy.stats.ttest_1samp(not_spayed_females, 0.5))

Ttest_1sampResult(statistic=6.530866646811577, pvalue=1.5561072684583303e-10)
Ttest_1sampResult(statistic=3.9869809503377502, pvalue=8.10117430677615e-05)
Ttest_1sampResult(statistic=5.321201889534012, pvalue=2.1678665057880635e-07)
Ttest_1sampResult(statistic=3.5213518802815558, pvalue=0.0005440186750103472)

In [71]:
pa_data = pd.read_csv('https://raw.githubusercontent.com/DanielleRomanoff/DS-Unit-1-Project_Dog_Bites/master/PA%20Dangerous%20Dogs%201996-Current.csv')
pa_data.shape
pa_data = pa_data[pa_data['Owner County'] != "OUT-OF-STATE (8)"]
pa_data = pa_data[pa_data['Owner County'] != "UNKNOWN (8)"]                 
pa_data.head()

,File Date,Determination Year,Status Description,County Description,Dog Info Age,Dog Info Breed,Dog Info Predator,County Key,Owner County,Court Disposition,Hearing Date,Owner First Name,Owner Last Name,Owner Address,Owner City,Owner State,Owner Zip,Location
0,12/12/2002,2002,Closed,BUCKS (7),2 YRS.,MIXED BREED,Dog,9,BUCKS (7),Guilty,02/28/2003,DAVID,GERSENSON,PO BOX 432,REVERE,PA,18953.0,"PO BOX 432\nREVERE, PA 18953"
1,06/30/2003,2003,Deceased,ALLEGHENY (4),11 YRS.,MIXED BREED,Dog,2,ALLEGHENY (4),Guilty,06/30/2003,SHANEA,NAKONECNY,2208 ORCHARD HILL ROAD,JEFFERSON HILLS,PA,15025.0,"2208 ORCHARD HILL ROAD\nJEFFERSON HILLS, PA 15025"
2,07/09/2003,2003,Deceased,BRADFORD (3),7 YRS.,Rottweiler,Dog,8,BRADFORD (3),Guilty,07/09/2003,THERON,WICKWIRE,"RR 2, BOX 100",WYSOX,PA,18854.0,"RR 2, BOX 100\nWYSOX, PA 18854"
3,06/10/2004,2004,Deceased,WESTMORELAND (4),ADULT,MIXED BREED,Dog,65,WESTMORELAND (4),Guilty,06/10/2004,VERONICA,SIMMS,RT 982 HOUSE 520,NEW DERRY,PA,15627.0,"RT 982 HOUSE 520\nNEW DERRY, PA 15627"
4,06/09/2004,2004,Closed,WYOMING (3),9 YRS.,Labrador Retriever,Dog,66,WYOMING (3),Guilty,06/03/2004,KIMBERLY,MERRYMAN,"RR 1, BOX 81",NOXEN,PA,18636.0,"RR 1, BOX 81\nNOXEN, PA 18636"

In [72]:
pa_data['County Description'] = pa_data['County Description'].str[:-4]
pa_data['County Description'] = pa_data['County Description'].str.lower()
pa_data.head()

,File Date,Determination Year,Status Description,County Description,Dog Info Age,Dog Info Breed,Dog Info Predator,County Key,Owner County,Court Disposition,Hearing Date,Owner First Name,Owner Last Name,Owner Address,Owner City,Owner State,Owner Zip,Location
0,12/12/2002,2002,Closed,bucks,2 YRS.,MIXED BREED,Dog,9,BUCKS (7),Guilty,02/28/2003,DAVID,GERSENSON,PO BOX 432,REVERE,PA,18953.0,"PO BOX 432\nREVERE, PA 18953"
1,06/30/2003,2003,Deceased,allegheny,11 YRS.,MIXED BREED,Dog,2,ALLEGHENY (4),Guilty,06/30/2003,SHANEA,NAKONECNY,2208 ORCHARD HILL ROAD,JEFFERSON HILLS,PA,15025.0,"2208 ORCHARD HILL ROAD\nJEFFERSON HILLS, PA 15025"
2,07/09/2003,2003,Deceased,bradford,7 YRS.,Rottweiler,Dog,8,BRADFORD (3),Guilty,07/09/2003,THERON,WICKWIRE,"RR 2, BOX 100",WYSOX,PA,18854.0,"RR 2, BOX 100\nWYSOX, PA 18854"
3,06/10/2004,2004,Deceased,westmoreland,ADULT,MIXED BREED,Dog,65,WESTMORELAND (4),Guilty,06/10/2004,VERONICA,SIMMS,RT 982 HOUSE 520,NEW DERRY,PA,15627.0,"RT 982 HOUSE 520\nNEW DERRY, PA 15627"
4,06/09/2004,2004,Closed,wyoming,9 YRS.,Labrador Retriever,Dog,66,WYOMING (3),Guilty,06/03/2004,KIMBERLY,MERRYMAN,"RR 1, BOX 81",NOXEN,PA,18636.0,"RR 1, BOX 81\nNOXEN, PA 18636"

In [87]:
pa_data_new = pa_data.groupby(['Dog Info Breed', 'Court Disposition', 'Status Description']).count().sort_values(by = ['Dog Info Breed', 'Location'], ascending = False)
pa_data_modified = pa_data_new.drop(index = ['UNKNOWN', 'OTHER', 'MIXED BREED', 'Mastiff'])
pa_bite_data = pa_data_modified[pa_data_modified['Location'] >= 25]
pa_bite_final = pd.DataFrame(pa_bite_data, columns = ['Location'])
pa_bite_final.head(10)

                                                                Location
Dog Info Breed            Court Disposition Status Description
Rottweiler                Guilty            Deceased                  57
                                            Closed                    40
                          Not Guilty        Closed                    38
                          Guilty            Deceased Dog              25
MIXED BREED: Pit Bull Mix Guilty            Euthanized                26
Labrador Retriever        Guilty            Deceased                  30
                          Not Guilty        Closed                    25
German Shepherd           Guilty            Deceased                  81
                          Not Guilty        Closed                    54
                          Other             Deceased                  51

In [74]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/minoritymajority.csv')
df_pa = df[df['STNAME'] == 'Pennsylvania']
df_pa['CTYNAME'] = df_pa['CTYNAME'].str[:-7]
df_pa['CTYNAME'] = df_pa['CTYNAME'].str.lower()
df_pa.head()

/Users/danielleromanoff/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/danielleromanoff/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,FIPS,STNAME,CTYNAME,TOT_POP,TOT_MALE,TOT_FEMALE,WA_MALE,WA_FEMALE,NHWA_MALE,NHWA_FEMALE,NHWhite_Alone,Not_NHWhite_Alone,MinorityMinority,MinorityPCT,Black,BlackPCT,Hispanic,HispanicPCT
1518,42001,Pennsylvania,adams,101482,49977,51505,47923,49467,44761,46897,91658,9824,No,9.68%,1798,2%,6343,6.25%
1519,42003,Pennsylvania,allegheny,1229338,590492,638846,483798,518237,475401,510245,985646,243692,No,19.82%,164288,13%,21733,1.77%
1520,42005,Pennsylvania,armstrong,68409,33869,34540,33182,33887,33013,33692,66705,1704,No,2.49%,572,1%,435,0.64%
1521,42007,Pennsylvania,beaver,170245,82348,87897,75233,80204,74342,79250,153592,16653,No,9.78%,10812,6%,2197,1.29%
1522,42009,Pennsylvania,bedford,49324,24559,24765,24076,24311,23840,24149,47989,1335,No,2.71%,288,1%,488,0.99%

In [75]:
decision = pa_data[pa_data['Court Disposition'] == 'Guilty']

euthanized = decision[decision['Status Description'] == 'Euthanized']
deceased = decision[decision['Status Description'] == 'Deceased']

guilty_euth = euthanized['Dog Info Breed'].value_counts()
guilty_deceased = deceased['Dog Info Breed'].value_counts()

zipcode_count = pa_data['Owner Zip'].value_counts()

In [76]:
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as ff

In [77]:
len(pa_data['Owner County'].value_counts())

67

In [78]:
# pa_data['Owner County'].value_counts()
# pa_data['FIPS'] = df_pa['FIPS']
pa_data = pa_data.merge(df_pa, left_on = 'County Description', right_on = 'CTYNAME', how = 'outer')
pa_data.head()

,File Date,Determination Year,Status Description,County Description,Dog Info Age,Dog Info Breed,Dog Info Predator,County Key,Owner County,Court Disposition,...,NHWA_MALE,NHWA_FEMALE,NHWhite_Alone,Not_NHWhite_Alone,MinorityMinority,MinorityPCT,Black,BlackPCT,Hispanic,HispanicPCT
0,12/12/2002,2002,Closed,bucks,2 YRS.,MIXED BREED,Dog,9,BUCKS (7),Guilty,...,264373.0,275890.0,540263.0,86790.0,No,13.84%,24398.0,4%,28566.0,4.56%
1,01/01/1997,1997,Closed,bucks,2 YRS.,MIXED BREED,Dog,9,BUCKS (7),Other,...,264373.0,275890.0,540263.0,86790.0,No,13.84%,24398.0,4%,28566.0,4.56%
2,01/01/1997,1997,Deceased,bucks,3 YRS.,MIXED BREED,Dog,9,BUCKS (7),Other,...,264373.0,275890.0,540263.0,86790.0,No,13.84%,24398.0,4%,28566.0,4.56%
3,01/01/2001,2001,Closed,bucks,NaN,OTHER,Dog,9,BUCKS (7),Other,...,264373.0,275890.0,540263.0,86790.0,No,13.84%,24398.0,4%,28566.0,4.56%
4,12/12/2002,2002,Closed,bucks,1 1/2 YR.,MIXED BREED,Dog,9,BUCKS (7),Guilty,...,264373.0,275890.0,540263.0,86790.0,No,13.84%,24398.0,4%,28566.0,4.56%

In [79]:
pa_data.columns

Index(['File Date', 'Determination Year', 'Status Description',
       'County Description', 'Dog Info Age', 'Dog Info Breed',
       'Dog Info Predator', 'County Key', 'Owner County', 'Court Disposition',
       'Hearing Date', 'Owner First Name', 'Owner Last Name', 'Owner Address',
       'Owner City', 'Owner State', 'Owner Zip', 'Location', 'FIPS', 'STNAME',
       'CTYNAME', 'TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE',
       'NHWA_MALE', 'NHWA_FEMALE', 'NHWhite_Alone', 'Not_NHWhite_Alone',
       'MinorityMinority', 'MinorityPCT', 'Black', 'BlackPCT', 'Hispanic',
       'HispanicPCT'],
      dtype='object')

In [80]:
pa_fips = pa_data.FIPS.value_counts()
pa_fips

42003.0    666
42133.0    499
42017.0    318
42129.0    315
42091.0    263
42071.0    212
42077.0    210
42045.0    210
42095.0    210
42049.0    191
42055.0    179
42029.0    162
42019.0    140
42043.0    121
42011.0    117
42089.0     93
42007.0     92
42041.0     91
42021.0     73
42085.0     69
42001.0     66
42079.0     64
42107.0     59
42027.0     58
42051.0     57
42083.0     53
42125.0     48
42069.0     47
42065.0     46
42101.0     45
42087.0     41
42009.0     41
42097.0     41
42063.0     40
42121.0     39
42013.0     38
42075.0     34
42015.0     34
42081.0     33
42103.0     33
42005.0     31
42039.0     29
42047.0     27
42033.0     25
42127.0     23
42031.0     23
42123.0     22
42111.0     22
42117.0     21
42073.0     18
42131.0     17
42059.0     17
42037.0     17
42035.0     15
42105.0     11
42025.0     10
42057.0     10
42099.0      9
42061.0      9
42115.0      9
42093.0      6
42067.0      6
42119.0      6
42053.0      5
42113.0      4
42109.0      3
42023.0      2
Name: FIPS, dtype: int64

In [81]:

plotly.tools.set_credentials_file(username='dlromanoff', api_key='9sTMPd6l0kHW68sZ6Xx2')
values = pa_fips
fips = pa_fips.index

endpts = list(np.mgrid[min(values):max(values):10j])
colorscale = ["rgb(102,0,0)", "rgb(76,0,153)", "rgb(0,0,102)", "rgb(255,0,0)", "rgb(153,153,255)", "rgb(255,51,51)","rgb(175, 122, 255)","rgb(255,246,122)","rgb(255,202,122)","rgb(255,122,202)","rgb(255,158,122)","rgb(128,0,117)"]
fig = ff.create_choropleth(
    fips = fips, values=values, scope=['Pennsylvania'], show_state_data=True,
    colorscale=colorscale, binning_endpoints=endpts, round_legend_values=True,
    plot_bgcolor='rgb(229,229,229)',
    paper_bgcolor='rgb(229,229,229)',
    legend_title='Dog Bites by County',
    county_outline={'color': 'rgb(255,255,255)', 'width': 0.5},
    exponent_format=True,
)
py.iplot(fig, filename='choropleth_pennsylvania')

/Users/danielleromanoff/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


/Users/danielleromanoff/anaconda3/lib/python3.6/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead

In [82]:
plotly.tools.set_credentials_file(username='dlromanoff', api_key='9sTMPd6l0kHW68sZ6Xx2')

x = ['American Staffordshire Terrier', 'Beagle', 'Boxer', 'Bull Dog', 'Chihuahua', 'Chow Chow', 'Cocker Spaniel', 'German Shepherd', 'Jack Russell', 'Labrador Retriever', 'Labrador Retriever Crossbreed', 'Maltese','Pit Bull', 'Pomeranian', 'Poodle', 'Rottweiler', 'Shiba Inu','Shih Tzu', 'Siberian Husky', 'Yorkshire Terrier']

trace0 = dict(
    x = x,
    y = ['10', '26', '15', '58', '68', '5', '27', '64', '36', '48', '31', '53', '259', '12', '14', '22', '20', '82', '28', '68'],
    fill = 'tonexty',
    mode='lines',
    name = 'Neutered Males',
    line=dict(width=0.5,
              color='rgb(184, 247, 212)'),
    stackgroup='one',
    groupnorm='percent'
)
trace1 = dict(
    x = x,
    y=['44', '11', '16', '43', '72', '16', '20', '69', '29', '28', '0', '39', '542', '19', '24', '42', '12', '11', '29', '41'],
    fill = 'tonexty',
    mode='lines',
    name = 'Unneutered Males',
    line=dict(width=0.5,
              color='rgb(111, 231, 219)'),
    stackgroup='one'
)
trace2 = dict(
    x = x,
    y=['3', '7', '0', '21', '24', '2', '6', '25', '0', '0', '0', '0', '154', '2', '7', '8', '10', '20', '9', '21'],
    fill = 'tonexty',
    mode='lines',
    name= 'Spayed Females',
    line=dict(width=0.5,
              color='rgb(127, 166, 238)'),
    stackgroup='one'
)
trace3 = dict(
    x = x,
    y=['4', '7', '0', '11', '26', '4', '12', '30', '0', '0', '0', '0', '219', '4', '8', '12', '6', '44', '8', '21'],
    fill = 'tonexty',
    mode='lines',
    name = 'Unspayed Females',
    line=dict(width=0.5,
              color='rgb(131, 90, 241)'),
    stackgroup='one'
)
data = [trace0, trace1, trace2, trace3]
layout = go.Layout(
    title = 'Dog Bites by Breed',
    showlegend=True,
    xaxis=dict(
        title = 'Breed',
        titlefont=dict(
            family='Overpass',
            size=18,
            color='#7f7f7f'
        ),
        type='category',
    ),
    yaxis=dict(
        title = 'Number of Bites',
        titlefont=dict(
            family='Overpass',
            size=18,
            color='#7f7f7f'
        ),
        type='linear',
        range=[1, 100],
        dtick=10
    )
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = 'stacked-area-plot-norm', validate = False)